version: 0.2

env:
    variables:
        environment: 'dev'
        STACK_NAME: 'tbd'
        STACK_VERSION: 'tbd'
        ECR_REPO: '/home-app'

phases:
    pre_build:
        commands:
            - chmod +x ./scripts/*.sh
    build:
        commands:
            - echo Build started on 'date'
            - ./scripts/dev_push.sh
            - aws s3  ls s3://s3-react-aws-home-app
        finally:
            - echo build phase finished
            - aws s3 cp * s3://s3-react-aws-home-app
            - aws s3  ls s3://s3-react-aws-home-app
    post_build:
        commands:
            - aws s3 sync build/ s3://s3-react-aws-home-app --delete --acl public-read --source-region us-east-2 --region us-east-2
            - echo Build completed on 'date'
