import * as action from './action-types'
const actionCreator = type => payload => ({ type, payload })

export const setUser = actionCreator(action.SET_USER)
export const setUserCode = actionCreator(action.SET_USER_CODE)
export const setSession = actionCreator(action.SET_SESSION)
export const setIdToken = actionCreator(action.SET_ID_TOKEN)
export const setAccessToken = actionCreator(action.SET_ACCESS_TOKEN)
export const setAuthorizedUser = actionCreator(action.SET_AUTHORIZED_USER)
export const setAuthLoading = actionCreator(action.SET_AUTH_LOADING)
export const setAuthFailed = actionCreator(action.SET_AUTH_FAILED)
export const setAuthenticated = actionCreator(action.SET_AUTH_SUCCESS)
export const registerUser = actionCreator(action.REGISTER_USER)
export const setUserPool = actionCreator(action.SET_USER_POOL)
export const loginUser = actionCreator(action.LOGIN_USER)
export const logoutUser = actionCreator(action.LOGOUT_USER)
export const confirmUser = actionCreator(action.CONFIRM_USER)
export const resendConfirmationCode = actionCreator(action.RESEND_CONFIRMATION_CODE)
export const getSignedInUser = actionCreator(action.GET_SIGNED_IN_USER)
